version: "3.8"

networks:
  iconloop:
    external: true

services:
  
  #********
  # CITIZEN
  #********

  citizen:
    networks:
      - iconloop
    healthcheck:
      disable: true
    ports:
      - mode: host
        target: 7100
        protocol: tcp
        published: 7100
      - mode: host
        target: 9000
        protocol: tcp
        published: 9000
    volumes:
      - ~/citizen:/cert
      - ~/citizen:/data
    image: iconloop/prep-node
    deploy:
      replicas: 3
      placement:
        preferences:
          - spread: node.labels.zone
    environment:
      CERT_PATH: "/cert"
      FASTEST_START: "yes"
      DEFAULT_PATH: "/data"
      TZ: "Asia/Ho_Chi_Minh"
      NETWORK_ENV: "mainnet"
      ICON_LOG_LEVEL: "ERROR"
      LOOPCHAIN_LOG_LEVEL: "ERROR"
      PRIVATE_PASSWORD: "Ico123!@#"
      PRIVATE_KEY_FILENAME: "citizen.keystore"
#     ENDPOINT_URL: "http://95.179.230.6:9000"
