version: "3.8"

networks:
  iconloop:
    external: true
  iconviet:
    external: true
  iconviet_production:
    external: true

services:
  
  #****
  # WEB
  #****
  
  web:
    ports:
      - mode: host
        target: 80
        protocol: tcp
        published: 8510
    networks:
      - iconloop
      - iconviet
      - iconviet_production
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
        preferences:
          - spread: node.labels.zone
    volumes:
      - /etc/hostname:/etc/hostname:ro
    command: >
      sh -c "export HOSTNAME=`cat /etc/hostname` &&
             dotnet Megaloop.Service.Web.dll"
    image: iconviet.azurecr.io/megaloop_production_web
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      ENVIRONMENT: "production"
      CITIZEN_URL: "http://172.18.0.1:9000"
      CONTRACT_ID: "cx7525d37107513415796e81326fc26a477721ab8c"

  #****
  # API
  #****

  api:
    ports:
      - mode: host
        target: 81
        protocol: tcp
        published: 8511    
    networks:
      - iconloop
      - iconviet
      - iconviet_production
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
        preferences:
          - spread: node.labels.zone
    image: iconviet.azurecr.io/megaloop_production_api
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      ENVIRONMENT: "production"
      CITIZEN_URL: "http://172.18.0.1:9000"
      CONTRACT_ID: "cx7525d37107513415796e81326fc26a477721ab8c"

  #****
  # JOB
  #****

  job:
    networks:
      - iconloop
      - iconviet
      - iconviet_production
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == manager
    image: iconviet.azurecr.io/megaloop_production_job
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      ENVIRONMENT: "production"
      CITIZEN_URL: "http://172.18.0.1:9000"
      CONTRACT_ID: "cx7525d37107513415796e81326fc26a477721ab8c"
