version: "3.8"

networks:
  iconloop:
    external: true
  iconviet:
    external: true
  iconviet_development:
    external: true

services:
  
  #****
  # WEB
  #****
  
  web:
    ports:
      - mode: host
        target: 80
        protocol: tcp
        published: 8310
    networks:
      - iconloop
      - iconviet
      - iconviet_development
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
        preferences:
          - spread: node.labels.zone
    volumes:
      - /etc/hostname:/etc/hostname:ro
    command: >
      sh -c "export HOSTNAME=`cat /etc/hostname` &&
             dotnet Megaloop.Service.Web.dll"
    image: iconviet.azurecr.io/megaloop_development_web
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      ENVIRONMENT: "development"
      CITIZEN_URL: "https://bicon.net.solidwallet.io"
      TRACKER_URL: "https://bicon.net.solidwallet.io"
      CONTRACT_ID: "cx24859f3c8ce069893b56703828af385faac611a0"

  #****
  # API
  #****

  api:
    ports:
      - mode: host
        target: 81
        protocol: tcp
        published: 8311    
    networks:
      - iconloop
      - iconviet
      - iconviet_development
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
        preferences:
          - spread: node.labels.zone
    image: iconviet.azurecr.io/megaloop_development_api
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      ENVIRONMENT: "development"
      CITIZEN_URL: "https://bicon.net.solidwallet.io"
      TRACKER_URL: "https://bicon.net.solidwallet.io"
      CONTRACT_ID: "cx24859f3c8ce069893b56703828af385faac611a0"

  #****
  # JOB
  #****

  job:
    networks:
      - iconloop
      - iconviet
      - iconviet_development
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == manager
    image: iconviet.azurecr.io/megaloop_development_job
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      ENVIRONMENT: "development"
      CITIZEN_URL: "https://bicon.net.solidwallet.io"
      TRACKER_URL: "https://bicon.net.solidwallet.io"
      CONTRACT_ID: "cx24859f3c8ce069893b56703828af385faac611a0"
