version: "3.8"

networks:
  iconloop:
    external: true
  iconviet:
    external: true
  iconviet_production:
    external: true

services:
  
  #****
  # WEB
  #****
  
  web:
    ports:
      - mode: host
        target: 80
        protocol: tcp
        published: 8510
    networks:
      - iconloop
      - iconviet
      - iconviet_production
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      ENVIRONMENT: "production"
    deploy:
      replicas: 3
      placement:
        preferences:
          - spread: node.labels.zone
    volumes:
      - /etc/hostname:/etc/hostname:ro
    command: >
      sh -c "export HOSTNAME=`cat /etc/hostname` &&
             dotnet Megaloop.Service.Web.dll"
    image: iconviet.azurecr.io/megaloop_production_web

  #****
  # API
  #****

  api:
    ports:
      - mode: host
        target: 81
        protocol: tcp
        published: 8511    
    networks:
      - iconloop
      - iconviet
      - iconviet_production
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      ENVIRONMENT: "production"
    deploy:
      replicas: 3
      placement:
        preferences:
          - spread: node.labels.zone
    image: iconviet.azurecr.io/megaloop_production_api

  #****
  # JOB
  #****

  job:
    networks:
      - iconloop
      - iconviet
      - iconviet_production
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      ENVIRONMENT: "production"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.labels.zone
    image: iconviet.azurecr.io/megaloop_production_job
