version: "3.7"

networks:
  iconviet:
    external: true

services:
  # NGINX
  nginx:
    depends_on:
      - teamcity
      - portainer
    image: iconviet/nginx:latest
    networks:
      - iconviet
    ports:
      - "80:80"
    volumes:
      - ~/volume/nginx:/etc/nginx
      - ~/volume/nginx/www:/etc/nginx/www
    deploy:
      resources:
        reservations:
          memory: 256M
        limits:
          memory: 512M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager

# MSSQL
  mssql:
    image: iconviet/mssql:latest
    networks:
      - iconviet
    ports:
      - "1433"
    volumes:
      - ~/volume/mssql:/var/opt/mssql/data
    deploy:
      resources:
        reservations:
          memory: 1024M
        limits:
          memory: 2048M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager

  # TEAMCITY
  teamcity:
    depends_on:
      - mssql
    image: iconviet/teamcity:latest
    networks:
      - iconviet
    ports:
      - "8111"
    volumes:
      - ~/volume/teamcity:/var/lib/teamcity
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        reservations:
          memory: 1024M
        limits:
          memory: 2048M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager

# PORTAINER
  portainer:
    image: iconviet/portainer:latest
    networks:
      - iconviet
    ports:
      - "9000"
    volumes:
      - ~/volume/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        reservations:
          memory: 32M
        limits:
          memory: 64M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager