version: "3.7"

networks:
  iconviet:
    external: true

services:
  # NGINX
  nginx:
    ports:
      - "80:80"
    networks:
      - iconviet
    image: iconviet/nginx
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
    volumes:
      - ~/volume/nginx:/etc/nginx
      - ~/volume/nginx/www:/etc/nginx/www

# MSSQL
  mssql:
    ports:
      - "1433"
    networks:
      - iconviet
    image: iconviet/mssql
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
    volumes:
      - ~/volume/mssql:/var/opt/mssql/data

  # TEAMCITY
  teamcity:
    ports:
      - "8111"
    networks:
      - iconviet
    image: iconviet/teamcity
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
    volumes:
      - ~/volume/teamcity:/var/lib/teamcity
      - /var/run/docker.sock:/var/run/docker.sock

# PORTAINER
  portainer:
    ports:
      - "9000"
    networks:
      - iconviet
    image: iconviet/portainer
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
    volumes:
      - ~/volume/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock