version: "3.7"

networks:
  iconviet:
    external: true

services:
  # WEB
  web:
    ports:
      - 80:80
    networks:
      - iconviet
    environment:
      - ENVIRONMENT=development
    deploy:
      replicas: 1
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
    image: iconviet.azurecr.io/iconlook_development_web

  # API
  api:
    ports:
      - 81:81
    networks:
      - iconviet
    environment:
      - ENVIRONMENT=development
    deploy:
      replicas: 1
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
    image: iconviet.azurecr.io/iconlook_development_api

  # JOB
  job:
    ports:
      - 82:82
    networks:
      - iconviet
    environment:
      - ENVIRONMENT=development
    deploy:
      replicas: 1
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
    image: iconviet.azurecr.io/iconlook_development_job