version: "3.7"

networks:
  iconviet:
    external: true

services:
  
  #****
  # WEB
  #****
  
  web:
    networks:
      - iconviet
    ports:
      - mode: host
        target: 80
        protocol: tcp
        published: 80
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      ENVIRONMENT: "development"
    deploy:
      replicas: 3
      placement:
        preferences:
          - spread: node.labels.zone
    volumes:
      - /etc/hostname:/etc/hostname:ro
    command: >
      sh -c "export HOSTNAME=`cat /etc/hostname` &&
             dotnet Iconlook.Service.Web.dll"
    image: iconviet.azurecr.io/iconlook_development_web

  #****
  # API
  #****

  api:
    networks:
      - iconviet
    ports:
      - mode: host
        target: 81
        protocol: tcp
        published: 81
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      ENVIRONMENT: "development"
    deploy:
      replicas: 3
      placement:
        preferences:
          - spread: node.labels.zone
    image: iconviet.azurecr.io/iconlook_development_api

  #****
  # JOB
  #****

  job:
    networks:
      - iconviet
    ports:
      - mode: host
        target: 82
        protocol: tcp
        published: 82
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      ENVIRONMENT: "development"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role != manager
        preferences:
          - spread: node.labels.zone
    image: iconviet.azurecr.io/iconlook_development_job

  #****
  # MON
  #****

  mon:
    networks:
      - iconviet
    ports:
      - mode: host
        target: 83
        protocol: tcp
        published: 83
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      ENVIRONMENT: "development"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role != manager
    image: iconviet.azurecr.io/iconlook_development_mon