version: "3.7"

networks:
  iconviet:
    external: true

services:
  # SEQ
  seq:
    networks:
      - iconviet
    ports:
      - 5341:5341
    image: iconviet/seq
    environment:
      ACCEPT_EULA: "Y"
      TZ: "Asia/Ho_Chi_Minh"
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager

  # MSSQL
  mssql:
    networks:
      - iconviet
    ports:
      - 1433:1433
    image: iconviet/mssql
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    volumes:
      - ~/:/var/opt/mssql/data
    deploy:
      replicas: 1
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.labels.zone

  # REDIS
  redis:
    networks:
      - iconviet
    ports:
      - 6379:6379
      - 26379:26379
    image: iconviet/redis
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    sysctls:
      net.core.somaxconn: 65535
    deploy:
      replicas: 1
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.labels.zone

  # RAVENDB
  ravendb:
    networks:
      - iconviet
    ports:
      - 8080:8080
      - 38888:38888
    image: iconviet/ravendb
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    deploy:
      replicas: 1
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.labels.zone

  # RABBITMQ
  rabbitmq:
    networks:
      - iconviet
    ports:
      - 5672:5672
      - 15672:15672
    image: iconviet/rabbitmq
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    deploy:
      replicas: 1
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.labels.zone

  # ELASTIC
  elastic:
    networks:
      - iconviet
    ports:
      - 5601:5601
      - 9200:9200
      - 9300:9300
    image: iconviet/elastic
    environment:
      - TZ="Asia/Ho_Chi_Minh"
      - "cluster.name=iconviet"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
    deploy:
      replicas: 1
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.labels.zone

  # PORTAINER
  portainer:
    networks:
      - iconviet
    ports:
      - 9000:9000
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    image: iconviet/portainer
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
    volumes:
      - ~/:/data
      - /var/run/docker.sock:/var/run/docker.sock

  # DOCKUPDATER
  dockupdater:
    networks:
      - iconviet
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    image: iconviet/dockupdater
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
    environment:
      - LATEST=true
      - INTERVAL=60
      - CLEANUP=true
      - DISABLE_CONTAINERS_CHECK=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/root/.docker/config.json
