version: "3.7"

networks:
  infrastructure:
    external: true

services:
  # NGINX
  nginx:
    ports:
      - 80:80
    networks:
      - infrastructure
    image: iconviet/nginx
    environment:
      ENVIRONMENT: "infrastructure"
    volumes:
      - ~/volume/nginx:/etc/nginx
      - ~/volume/nginx/www:/etc/nginx/www
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
          - node.labels.environment == infrastructure

  # MSSQL
  mssql:
    ports:
      - 1433
    networks:
      - infrastructure
    image: iconviet/mssql
    environment:
      ENVIRONMENT: "infrastructure"
    volumes:
      - ~/volume/mssql:/var/opt/mssql/data
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
          - node.labels.environment == infrastructure

  # TEAMCITY
  teamcity:
    ports:
      - 8111
    networks:
      - infrastructure
    image: iconviet/teamcity
    environment:
      ENVIRONMENT: "infrastructure"
    volumes:
      - ~/volume/teamcity:/var/lib/teamcity
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
          - node.labels.environment == infrastructure

  # PORTAINER
  portainer:
    ports:
      - 9000
    networks:
      - infrastructure
    image: iconviet/portainer
    environment:
      ENVIRONMENT: "infrastructure"
    volumes:
      - ~/volume/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
          - node.labels.environment == infrastructure