#!/bin/bash
echo -e "\e[1;32m[1/2] Initializing swarm \e[0m"
docker swarm init --advertise-addr 10.1.0.4
echo -e "\e[1;32m[2/2] Creating overlay network\e[0m"
docker network create --driver overlay --subnet 10.1.0.0/28 infrastructure
docker network create --driver overlay --subnet 10.1.1.0/28 development
docker network create --driver overlay --subnet 10.1.2.0/28 production
